### ISSUE TITLE
Question: JSON Map

### ISSUE THREAD

**Issue by Zultralord** [DylanDodds/PokeTwitch-Base#3]
Why is the map in a json format? Why not a tiled bitmap or some other image? What is the significance?

**Comment by OrthoLabs** [comment]
Being in JSON instead of being a raw image allows us to break all of the art into separate files. If every single map was a static image, this would be a LOT of data, and a lot of waste. It would make re-using assets harder as well, being baked into each map. This also allows us to add things like collisions onto the map is json objects, as well as other objects in general that we can dynamically load. Because Dylan's plan for this is to include multiplayer, it also means we can have the client have all of the art, and then we can send them a json file to load themselves as a map using their already-loaded assets.

**Comment by Zultralord** [comment]
Wow now that's smart. Makes me wonder how Gameboy managed to get by with only a game cartridge...

**Comment by OrthoLabs** [comment]
As someone who has worked a little bit with older systems, specifically the NES, they do it in a very similar way. Just more compact data, and they actually didn't have to render as much. I would definitely advise getting VBA or something and loading up a free ROM and just looking at the different debug options to see the maps and palette system and how those are laid out. Very interesting looking at the older technology.

**Comment by OrthoLabs** [comment]
Also, for future reference. If you ever want to contact me directly, I keep an IRC client up in Dolan's twitch channel. So if you ping me and I'm awake, I should respond fairly quickly. :P
